-- ================================================================
-- SEED VERİSİ — ARTIK KULLANILMIYOR
-- ================================================================
-- Gerçek ürün kataloğu (5 kategori / ~198 ürün) tamamen migration
-- dosyalarında tutulur (0012 ve sonrası). Yeni bir ortam kurarken
-- yalnızca migration'ları uygulamak yeterlidir:
--
--   supabase db push          (uzak/linked proje)
--   supabase db reset         (yerel geliştirme — tüm migration'ları çalıştırır)
--
-- Bu dosya bilerek boş bırakıldı; buraya demo/örnek veri EKLEMEYİN.
-- Katalog değişiklikleri sıralı migration olarak yazılır (bkz. CLAUDE.md).
--
-- Admin kullanıcısı: önce Supabase Auth üzerinden kullanıcı oluşturun, sonra:
--   update public.profiles set role = 'admin' where id = '<kullanicinin-uuid-si>';
-- ================================================================
